services:
  - type: web
    name: emossdev-panel
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER_ENVIRONMENT
        value: true
